Repository tamimattafi/krop, pull requests merged in 2024-09, with the labels that each got.

#6 Fix readme code: Use the actual factory method instead of the Interface
  README.md
Labels: documentation

#7 config: migrate to kotlin 2.0
  build.gradle.kts
  gradle/libs.versions.toml
  library/core/build.gradle.kts
  library/ui/build.gradle.kts
  plugins/publishing/src/main/kotlin/com/attafitamim/krop/publish/PublishConventions.kt
  sample/composeApp/build.gradle.kts
Labels: enhancement

#10 Zooming improvements
  library/core/src/commonMain/kotlin/com/attafitamim/krop/core/crop/CropState.kt
  library/core/src/commonMain/kotlin/com/attafitamim/krop/core/crop/Touch.kt
  library/core/src/commonMain/kotlin/com/attafitamim/krop/core/utils/Rect.kt
  library/core/src/commonMain/kotlin/com/attafitamim/krop/core/utils/ViewMat.kt
  library/core/src/commonMain/kotlin/com/attafitamim/krop/core/utils/ZoomLimits.kt
  library/ui/src/commonMain/kotlin/com/attafitamim/krop/ui/CropperPreview.kt
  library/ui/src/desktopTest/kotlin/com/attafitamim/krop/ui/CropStateTest.kt
Labels: enhancement

#11 Fix issue with first touch event
  gradle/libs.versions.toml
  library/core/src/commonMain/kotlin/com/attafitamim/krop/core/utils/GestureState.kt
Labels: bug

#12 Fix: maxSize ignored when clipping shape on save
  library/core/src/commonMain/kotlin/com/attafitamim/krop/core/crop/Result.kt
  library/core/src/commonMain/kotlin/com/attafitamim/krop/core/utils/Rect.kt
Labels: bug
